In [289]:
import pandas as pd
import numpy as np
from sklearn import decomposition
import matplotlib.pyplot as plt

In [290]:
dataset = pd.read_csv("career_compute_dataset.csv")

In [291]:
data = dataset.iloc[:49,:-1].values
label = dataset.iloc[:49,-1].values
data

array([[2, 3, 2, ..., 3, 4, 5],
       [3, 1, 2, ..., 3, 3, 4],
       [3, 4, 2, ..., 3, 3, 4],
       ...,
       [4, 3, 2, ..., 4, 3, 3],
       [2, 3, 2, ..., 3, 3, 1],
       [4, 3, 3, ..., 3, 3, 5]], dtype=object)

In [292]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder

In [293]:
labelencoder = LabelEncoder()

In [294]:
label = labelencoder.fit_transform(label)
label

array([4, 2, 6, 4, 1, 5, 7, 4, 5, 3, 2, 4, 7, 2, 2, 7, 5, 2, 4, 5, 4, 0,
       7, 2, 5, 6, 2, 7, 0, 7, 4, 2, 5, 0, 6, 2, 3, 2, 1, 4, 2, 3, 0, 7,
       4, 3, 4, 1, 2], dtype=int64)

In [295]:
y=pd.DataFrame(label,columns=["role"])
X1 = pd.DataFrame(data,columns=['sslc','hsc','cgpa','school_type','no_of_miniprojects','no_of_projects','coresub_skill','aptitude_skill','problemsolving_skill','programming_skill','abstractthink_skill','design_skill','first_computer','first_program','lab_programs','ds_coding','technology_used','sympos_attend','sympos_won','extracurricular','learning_style','college_bench','clg_teachers_know','college_performence','college_skills'])

In [296]:
from sklearn.preprocessing import Normalizer
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing 
from sklearn.metrics import accuracy_score

In [297]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.2,random_state=20)

In [298]:
clf = tree.DecisionTreeClassifier()
clf = clf.fit(X_train, y_train)

In [299]:
from sklearn.metrics import confusion_matrix,accuracy_score


In [300]:
y_pred = clf.predict(X_test)
print(y_pred)

[3 4 7 4 5 3 2 2 6 0]


In [301]:
cm = confusion_matrix(y_test,y_pred)
accuracy = accuracy_score(y_test,y_pred)
len(cm[1])

8

In [304]:
print("confusion matrics=",cm)
print("  ")
print("accuracy=",accuracy*100)

confusion matrics= [[0 0 0 0 0 0 0 0]
 [0 0 0 1 0 0 0 0]
 [1 0 2 0 0 1 0 0]
 [0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 1 0 0 1]
 [0 0 0 0 0 0 0 0]
 [0 0 0 1 1 0 0 0]]
  
accuracy= 20.0


In [305]:
X_train,X_test,y_train,y_test=train_test_split(X1,y,test_size=0.3,random_state=10)

In [306]:
X_train.shape

(34, 25)

In [307]:
X_train=pd.to_numeric(X_train.values.flatten())

In [308]:
X_train=X_train.reshape((34,25))

In [309]:
from xgboost.sklearn import XGBClassifier

In [310]:
model = XGBClassifier()
model.fit(X_train, y_train)

C:\anaconda\lib\site-packages\sklearn\preprocessing\label.py:95: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\anaconda\lib\site-packages\sklearn\preprocessing\label.py:128: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [311]:
xgb_y_pred  = clf.predict(X_test)

In [312]:
xgb_cm = confusion_matrix(y_test,xgb_y_pred)
xgb_accuracy = accuracy_score(y_test,xgb_y_pred)

In [313]:
print("confusion matrics=",xgb_cm)
print("  ")
print("accuracy=",xgb_accuracy*100)

confusion matrics= [[1 0 0 0 0 0 0]
 [0 3 0 0 0 0 0]
 [0 0 1 0 0 0 0]
 [0 0 0 5 0 1 0]
 [0 0 0 0 1 0 0]
 [0 0 0 0 0 1 0]
 [0 0 0 0 0 0 2]]
  
accuracy= 93.33333333333333


In [322]:
import seaborn as sns
from sklearn.neighbors import KNeighborsClassifier

In [342]:
dt=dataset.iloc[:49,]
dt

sslc  hsc  cgpa  school_type  no_of_miniprojects  no_of_projects  \
0      2    3     2            3                   1               1   
1      3    1     2            2                   2               1   
2      3    4     2            2                   1               1   
3      3    4     2            1                   1               1   
4      2    3     2            4                   1               1   
5      1    1     1            1                   1               1   
6      3    3     2            2                   2               1   
7      3    3     2            2                   1               1   
8      3    2     3            3                   1               1   
9      4    4     2            2                   1               1   
10     4    4     2            2                   1               1   
11     4    4     3            1                   1               1   
12     3    3     3            2                   1               1   
13     4    4     2            2                   1               1   
14     4    3     1            1                   1               1   
15     4    3     3            2                   1               1   
16     2    3     1            2                   2               1   
17     4    4     4            2                   2               1   
18     3    3     2            1                   1               1   
19     4    4     4            2                   2               1   
20     2    2     2            2                   1               1   
21     4    4     3            2                   1               1   
22     1    1     2            3                   3               3   
23     4    4     4            1                   2               2   
24     4    4     3            2                   2               1   
25     3    3     3            1                   1               1   
26     3    3     2            1                   1               1   
27     4    4     2            2                   2               1   
28     2    4     2            3                   2               2   
29     4    4     4            3                   2               1   
30     3    4     1            2                   1               1   
31     4    4     3            2                   2               1   
32     4    4     3            3                   1               1   
33     4    4     4            2                   2               1   
34     4    4     3            2                   1               1   
35     4    2     2            1                   1               1   
36     4    4     3            2                   1               1   
37     4    4     3            2                   2               1   
38     4    4     4            2                   1               1   
39     4    3     3            3                   2               1   
40     4    4     4            2                   2               1   
41     4    3     2            2                   1               1   
42     1    1     2            2                   2               2   
43     4    3     2            2                   2               1   
44     3    3     3            2                   1               2   
45     3    3     1            1                   1               1   
46     4    3     2            1                   2               1   
47     2    3     2            3                   1               1   
48     4    3     3            2                   2               1   

    coresub_skill  aptitude_skill  problemsolving_skill  programming_skill  \
0               1               1                     2                  4   
1               1               3                     2                  4   
2               1               2                     3                  3   
3               1               1                     3                  2   
4            

In [341]:
y = dt['ROLE'].values
X = dt.drop('ROLE', axis=1).values
knn = KNeighborsClassifier(n_neighbors=6)
knn.fit(X,y)
y_pred = knn.predict(X)
x_new = ['3','5','4','3','5','4','3','5','2','2','5','2','5','4','2','5','5','3','2','5','5','4','2','3','4']
new_pred = knn.predict([x_new])
print("Prediction : {}".format(new_pred))

Prediction : ['Web Developer']
